version: "3.9"

services:
  incentive-provider:
    container_name: incentive-provider
    build:
      context: .
    # dockerfile: Dockerfile.production
    ports:
      - "5011:5000"
    networks:
        - offer-enhancer-net


networks:
  offer-enhancer-net:
    external:
      name: trias-extractor_offer-enhancer-net